create table if not exists public.wallets (
    id bigint generated by default as identity primary key,
    user_id text not null unique,
    ltc text,
    btc text,
    eth text,
    sol text,
    usdt text,
    bnb text,
    xrp text,
    doge text,
    trx text,
    ton text,
    ada text,
    dot text,
    avax text,
    matic text,
    pol text,
    link text,
    shib text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists wallets_user_id_idx on public.wallets(user_id);

alter table public.wallets enable row level security;

-- The bot uses the Supabase service-role key server-side.
-- Do NOT expose that key in a Discord command, browser, or public frontend.
-- No public RLS policy is needed for this bot.
